/*
 * Unstructured Pipeline API
 * At Unstructured, we're on a mission to give organizations access to all of their data. We know the world runs on documents—from research reports and memos, to quarterly filings and plans of action, documents are the unit of information that companies depend on. And yet, 80% of this information is trapped in inaccessible formats, and businesses have long struggled to unlock this data, leading to information silos, inefficient decision-making, and repetitive work. Until now.  Unstructured captures this unstructured data wherever it lives and transforms it into AI-friendly JSON files for companies who are eager to fold AI into their business.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.io.File;
import com.konfigthis.client.model.PartitionParameters;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GeneralApi
 */
@Disabled
public class GeneralApiTest {

    private static GeneralApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new GeneralApi(apiClient);
    }

    /**
     * Pipeline 1
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createPipelineTest() throws ApiException {
        File files = null;
        String strategy = null;
        String gzUncompressedContentType = null;
        String outputFormat = null;
        Boolean coordinates = null;
        String encoding = null;
        String hiResModelName = null;
        Boolean includePageBreaks = null;
        List<String> languages = null;
        Boolean pdfInferTableStructure = null;
        List<String> skipInferTableTypes = null;
        Boolean xmlKeepTags = null;
        String chunkingStrategy = null;
        Boolean multipageSections = null;
        Integer combineUnderNChars = null;
        Integer newAfterNChars = null;
        Integer maxCharacters = null;
        Integer overlap = null;
        Boolean overlapAll = null;
        List<String> extractImageBlockTypes = null;
        List<Object> response = api.createPipeline()
                .files(files)
                .strategy(strategy)
                .gzUncompressedContentType(gzUncompressedContentType)
                .outputFormat(outputFormat)
                .coordinates(coordinates)
                .encoding(encoding)
                .hiResModelName(hiResModelName)
                .includePageBreaks(includePageBreaks)
                .languages(languages)
                .pdfInferTableStructure(pdfInferTableStructure)
                .skipInferTableTypes(skipInferTableTypes)
                .xmlKeepTags(xmlKeepTags)
                .chunkingStrategy(chunkingStrategy)
                .multipageSections(multipageSections)
                .combineUnderNChars(combineUnderNChars)
                .newAfterNChars(newAfterNChars)
                .maxCharacters(maxCharacters)
                .overlap(overlap)
                .overlapAll(overlapAll)
                .extractImageBlockTypes(extractImageBlockTypes)
                .execute();
        // TODO: test validations
    }

}
